[workspace]

members = [
    "rock-n-rollup",
    "kernel-macro",
    "examples/hello-world",
    "examples/read-input",
    "examples/magic-byte",
    "examples/store",
    "examples/database-example"
]