[workspace]

members = [
    "rock-n-rollup",
    "kernel-macro",
    "examples/hello-world",
    "examples/read-input",
    "examples/preimage",
    "examples/upgrade-kernel",
    "examples/everything",
    "examples/database"
]