[workspace]

members = [
    "rock-n-rollup",
    "kernel-macro",
    "examples/database",
    "examples/hello-world",
    "examples/read-input",
    "examples/preimage",
    "examples/upgrade-kernel",
    "examples/ping-pong",
    
]